#pragma once

#include "glwx/aabb.hpp"
#include "glwx/buffers.hpp"
#include "glwx/debug.hpp"
#include "glwx/math.hpp"
#include "glwx/mesh.hpp"
#include "glwx/meshgen.hpp"
#include "glwx/rendertarget.hpp"
#include "glwx/shader.hpp"
#include "glwx/spriterenderer.hpp"
#include "glwx/texture.hpp"
#include "glwx/transform.hpp"
#include "glwx/transform2d.hpp"
#include "glwx/utility.hpp"
#include "glwx/vertexaccessor.hpp"
#include "glwx/window.hpp"
